# Generated by Django 4.2.5 on 2023-09-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastexcel', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='companyname',
        ),
    ]
