# Generated by Django 4.2.5 on 2023-09-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastexcel', '0004_rename_username_customuser_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
